version: '3'
services:
  # web:
  #   image: httpd
  #   ports:
  #     - 80:80
  #   logging:
  #     driver: "fluentd"
  #     options:
  #       fluentd-address: 172.65.0.15:24224 # static IP address of the Fluentd service
  #       tag: httpd.access

  stacktrace:
    image: stacktrace:latest
    environment:
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=rabbit
      - RABBITMQ_PASSWORD=rabbit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 172.65.0.15:24224 # static IP address of the Fluentd service
        tag: java

networks:
  default:
    name: fluentd-network
    external: true